str_config = {
  'loss': 'ccl',
  'lr': 0.0005,
  'loss_neg_n': 1000,
  'loss_neg_k': 4,
  'loss_neg_w': 0.5,
  'weight_decay': 0.000001,
  'batch_size': 1024,
  'n_epoch': 1,
  'latent_dim': 128,
  'affinity': 'dot',
  'aggregate': 'weighted-sum',
  'cf_w': 0.8,
  'dropout': 0.2,
  'n_interactive_items': 16,
  'popular_alpha': 0.2,
  'group_loss_gamma': 0.2,
  'item_dropout': 0.6,
}

str_config_yelp = {
  'loss': 'ccl',
  'lr': 1e-4,
  'loss_neg_n': 1000,
  'loss_neg_k': 32,
  'loss_neg_w': 0.5,
  'weight_decay': 1e-6,
  'batch_size': 1024,
  'n_epoch': 100,
  'latent_dim': 64,
  'affinity': 'cos',
  'aggregate': 'mean',
  # 'attention_head': 8,
  'cf_w': 0.8,
  'dropout': 0.1,
  'n_interactive_items': 32,
  'popular_alpha': 0.1,
  'item_dropout': 0.9,
}

str_config_best_yelp = {
  'loss': 'ccl',
  'lr': 1e-4,
  'loss_neg_n': 300,
  'loss_neg_k': 0.5,
  'loss_neg_w': 0.5,
  'weight_decay': 1e-6,
  'batch_size': 512,
  'n_epoch': 100,
  'latent_dim': 64,
  'affinity': 'cos',
  'aggregate': 'mean',
  'cf_w': 0.8,
  'dropout': 0.1,
  'n_interactive_items': 32,
  'popular_alpha': 0.2,
  'item_dropout': 0.9,
}


str_config_gowalla = {
  'lr': 1e-3,
  'loss_neg_n': 2000,
  'loss_neg_a': 1.5,
  'loss_neg_w': 50,
  'loss_neg_m': .2,
  'weight_decay': 0,
  'batch_size': 512,
  'affinity': 'cos',
  'n_epoch': 100,
  'latent_dim': 64,
  'aggregate': 'weighted-sum',
  'cf_w': 0.3,
  'n_interactive_items': 64,
  'popular_alpha': 0,
  'group_loss_gamma': 0,
  'dropout': .5,
  'item_dropout': .5,
}

simplex_config = {
  'loss': 'ccl',
  'lr': 0.0003,
  'loss_neg_n': 1000,
  'loss_neg_k': 0.9,
  'loss_neg_w': 150,
  'weight_decay': 1e-8,
  'batch_size': 1024,
  'n_epoch': 20,
  'latent_dim': 128,
  'affinity': 'cos',
  # 'n_interactive_items': 32,
  'aggregate': 'mean',
  'cf_w': 1,
  'dropout': 0.1,
}

mf_bpr_config = {
  'batch_size': 512,
  'n_epoch': 50,
  'latent_dim': 64,
  'lr': 0.003,
  'weight_decay': 1e-8,
}


simplex_config_bak = {
  'loss': 'ccl',
  'lr': 1e-4,
  'loss_neg_n': 1000,
  'loss_neg_k': 0.9,
  'loss_neg_w': 150,
  'weight_decay': 1e-6,
  'batch_size': 512,
  'n_epoch': 50,
  'latent_dim': 256,
  'affinity': 'cos',
  'aggregate': 'mean',
  'cf_w': 1,
  'dropout': 0.1
}

str_config_yelp = {
  'loss': 'ccl',
  'lr': 1e-4,
  'loss_neg_n': 100,
  'loss_neg_k': 0.5,
  'loss_neg_w': 50,
  'weight_decay': 1e-6,
  'batch_size': 512,
  'n_epoch': 100,
  'latent_dim': 128,
  'affinity': 'cos',
  'aggregate': 'self-attention',
  'attention_head': 16,
  'cf_w': 0,
  'dropout': 0.1,
  'n_interactive_items': 32,
}

simplex_config_1 = {
  'loss': 'ccl',
  'lr': 1e-4,
  'loss_neg_n': 100,
  'loss_neg_k': 0.5,
  'loss_neg_w': 50,
  'weight_decay': 1e-6,
  'batch_size': 512,
  'n_epoch': 100,
  'latent_dim': 128,
  'affinity': 'cos',
  'aggregate': 'mean',
  'attention_head': 8,
  'cf_w': 0,
  'dropout': 0.1,
  'n_interactive_items': 8,
}

